version: "3.6"

services:
  scrapyd:
    image: zwilson/docker-scrapyd
    build: .
    volumes:
      - items:/usr/src/items
    configs:
      - source: scrapyd.conf
        target: /etc/scrapyd/scrapyd.conf
      - source: scrapy.cfg
        target: /usr/src/scrapy.cfg
    depends_on:
      - splash
    command: scrapyd
  splash:
    image: scrapinghub/splash
  spiderkeeper:
    image: zwilson/docker-spiderkeeper
    ports:
      - 5000:5000
    command: spiderkeeper --verbose --server=http://scrapyd:6800
  filebrowser:
      image: hacdias/filemanager
      ports:
          - 8000:80
      volumes:
          - items:/srv
volumes:
  items:

configs:
  scrapyd.conf:
    external: true
  scrapy.cfg:
    external: true
  nginx.conf:
    external: true
  Caddyfile:
    external: true
# secrets:
#   cert:
#     external: true
#   cer.key:
#     external: true
