version: "3.6"

services:

  scrapyd:
    image: zwilson/scrapyd
    build: .
    env_file: .env
    volumes:
      - items:/usr/src/items
    configs:
      - source: scrapyd.conf
        target: /etc/scrapyd/scrapyd.conf
    ports:
      - 6800:6800
    command: scrapyd

volumes:
  items:

configs:
  scrapyd.conf:
    external: true
