version: "3.6"

services:

  scrapyd:
    image: zwilson/docker-scrapyd
    build: .
    env_file: .env
    volumes:
      - items:/usr/src/items
    configs:
      - source: scrapyd.conf
        target: /etc/scrapyd/scrapyd.conf
    ports:
      - 6800:6800
    command: scrapyd

  web:
    image: nginx
    ports:
      - 80:80
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf

volumes:

  items:

configs:

  scrapyd.conf:
    external: true

  nginx.conf:
    external: true
